8 SummerSession1-main/backend/djangoreact/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
]

8 SummerSession1-main/backend/post/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', ListPost, name='ListPost'),
]

main/urls.py
from django.urls import path
from .views import *

app_name='main'
urlpatterns = [
    path('', main, name="showmain"), #main - views.py , showmain - template 
    path('show/', show, name="showintro"),
    path('detail/<int:id>/', detail, name="detail"),
    #path('posts/', posts, name="posts"),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('edit/<int:id>/', edit, name="edit"),
    path('update/<int:id>/', update, name="update"),
    path('delete/<int:id>/', delete, name="delete"),
]

sns_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

8 SummerSession1-main/backend/post/models.py
from django.db import models

# Create your models here.
#@0622
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()

    def __str__(self):
        return self.title

main/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title =models.CharField(max_length=200)
    writer = models.CharField(max_length=100)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to = "blog/", blank=True, null=True)

    def __str__(self):
        return self.title
    
    def summary(self):
        return self.body[:20]

8 SummerSession1-main/backend/post/views.py
from django.shortcuts import render

# Create your views here.

#@0622
# Response 추가
from rest_framework.response import Response
# HTTP method를 처리하기 위한 api_view 데코레이터 추가
from rest_framework.decorators import api_view

from .models import Post
# serializers에서 Postserializer를 가져옴
from .serializers import PostSerializer

# 포스트 리스트 뷰
@api_view(['GET'])
def ListPost(request):
    # GET 방식을 받아왔을 때
    if request.method == 'GET':
        posts = Post.objects.all()
        serializer = PostSerializer(posts, many=True)
        return Response(data=serializer.data)

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .models import Post

# Create your views here.
def main(request):
    return render(request, 'main/mainpage.html')
    
def show(request):
    return render(request, 'main/show.html')

def new(request):
    return render(request, 'main/new.html')

def create(request):
    new_post = Post()
    new_post.title = request.POST['title']
    new_post.writer = request.POST['writer']
    new_post.pub_date = timezone.now()
    new_post.body = request.POST['body']
    new_post.image = request.FILES.get('image')
    new_post.save()
    return redirect('main:detail', new_post.id)

def detail(request, id):
    blog = get_object_or_404(Post, pk = id)
    return render(request, 'main/detail.html', {'blog': blog})

def update(request, id):
    update_post = Post.objects.get(id = id)
    update_post.title = request.POST['title']
    update_post.writer = request.POST['writer']
    update_post.pub_date = timezone.now()
    update_post.body = request.POST['body']
    update_post.save()
    return redirect('main:detail', update_post.id)

def edit(request, id):
    edit_post = Post.objects.get(id = id)
    return render(request, 'main/edit.html', {'post' : edit_post })

def delete(request, id):
    delete_post = Post.objects.get(id = id)
    delete_post.delete()
    return redirect('main:main')

basic/templates/basic.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style_mainpage.css' %}">
    <st
        @import url('https://fonts.googleapis.com/css2?family=Noto+Serif+KR&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Song+Myung&display=swap');
    </style>
    <style>
        ::selection {
            background-color: #ec9119;
            color: rgb(31, 109, 182);
        }
    </style>
    <style>
    .thirsty:hover {
        background: linear-gradient(to Top, #ff60dd, rgba(28, 115, 255, 0.575));
        color: transparent;
        -webkit-background-clip: text;
    }
    </style>
</head>
<body>
    {% include 'shared/_navbar.html' %}

    <section class="container">
        {% block content %}
        
        {% endblock %}
    </section>
</body>
</html>

basic/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
        </li>
        </ul>
        <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
    </div>
</nav>

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>{{post.title}}</h1>
글쓴이 : {{post.writer}}
날짜 : {{post.pub_date}}
<hr>
{% if post.image %}
    <p><img src="{{ post.image.url }}" alt="사진"></p>
{% endif %}


<p>{{post.body}}</p>
<br><br>
<hr>
<a href="{% url 'main:edit' post.id %}">수정하기</a>
<a href="{% url 'main:delete' post.id %}">삭제하기</a>
{% comment %} <h5><a href="{% url 'main:posts' %}">목록</a></h5> {% endcomment %}

{% endblock %}

main/templates/main/new.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form action="{% url 'main:create' %}" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    <p>제목 : <input type="text" name="title"></p>
    <p>작성자 : <input type="text" name="writer"></p>
    <p>사진 : <input type="file" name="image"></p>
    <p>내용 : <textarea type="text" name="body" id="" cols"30" rows="10"></textarea></p>
    <button type="submit">제출</button>
</form>

{% endblock %}

main/templates/main/show.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>송영창</title>
    <link rel="stylesheet" href="{% static 'css/style_show.css' %}">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Noto+Serif+KR&display=swap');
    </style>

    <style type="text/css">
        /* link - 아직 클릭하지 않은 경우 red 색상 설정 */
        a:link {
            color: rgb(145, 170, 209);
            text-decoration: none;
        }

        /* visited - 한번 클릭하거나 전에 클릭한적 있을 경우 #c71d44 설정 */
        a:visited {
            color: rgb(145, 170, 209);
            text-decoration: none;
        }

        /* hover - 마우스를 해당 링크에 위치했을 경우 설정 */
        a:hover {
            color: #ec9119;
            /*text-decoration: line-through;*/
        }

        .header:hover {
            background: linear-gradient(to Top, #f5a666, rgba(145, 170, 209, 0.575));
            color: transparent;
            -webkit-background-clip: text;
        }
    </style>

    <style>
        ::selection {
            background-color: #ec9119;
            color: rgb(31, 109, 182);
        }
    </style>
    
</head>

<body bgcolor="#4F5AC1">

    <section class="container">

        <div class="wave" id="up">
            <!--송영창<br>송영창<br>송영창<br>-->
            <a href="https://www.instagram.com/doxo_psal/">
                <img style="max-width: 100%; height: auto;"
                    src="https://drive.google.com/uc?export=view&id=1TWhapumTFEefk11Pr-7WYxaZr7Yv2Q1u">
            </a>
            <p>
                <marquee direction="down" height="100">
                    <p style="text-align:center;"> <a href="#down"> ▼ </a> </p>
                </marquee>
            </p>
        </div>

        <article>
            <br><br><br><br><br><br><br><br>
        </article>

        <div class="header">
            <h1 class="hi">" 안녕하세요 "</h1>
            <p class="major">- 저는 전자전기공학부 송영창입니다.</p>
        </div>

        <article>
            <br><br><br><br><br><br><br><br>
            <br><br><br><br><br><br><br><br>
        </article>

        <div class="soundcloud">
            <p style="text-align:center;">
                <iframe width="100%" height="1000" scrolling="no" frameborder="no" allow="autoplay"
                    src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/661261982&color=%2391aad1&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>
            </p>
        </div>

        <article>
            <br><br><br><br><br><br><br><br>
        </article>

        <div class="content">
            <p class="sanserif">
            <h1>
                INFO
            </h1>
            </p>
            <p class="serif">
                생&nbsp;&nbsp;&nbsp;&nbsp;일 |
                <a href="https://acegif.com/wp-content/uploads/tort-11.gif"
                    onclick="window.open(this.href, '_blank', 'width=498px,height=280px,toolbars=no,scrollbars=no'); return false;">
                    <I>9월 2일</I>
                </a>
            </p>
            <p class="serif">
                깉&nbsp;&nbsp;&nbsp;&nbsp;헙 |
                <a href="https://github.com/ufo305/likelion10th" class="serif"> <I>ufo305</I> </a>
            </p>

            <!--p class="serif">
                동아리 |
                <a href="http://dgulion.co.kr/" class="club"> <I>멋쟁이 사자처럼 10기</I> </a>
            </p-->

            <p class="serif">
                사는곳 |
                <a href="https://images-assets.nasa.gov/image/PIA00076/PIA00076~orig.jpg"
                    onclick="window.open(this.href, '_blank', 'width=500px,height=500px,toolbars=no,scrollbars=no'); return false;">
                    <I>I'm here.</I>
                </a>

            </p>

            <!--p>
                    scenery |
                    <a href="https://images.squarespace-cdn.com/content/v1/53532f09e4b0339b7ca97d37/1580390580787-KAQ7B8NIGHAQA7RM15B5/1_1.7.1.jpg?format=1500w"
                        onclick="window.open(this.href, '_blank', 'width=1500px,height=844px,toolbars=no,scrollbars=no'); return false;">
                        <I>view</I>
                    </a>   
                </p-->

            <!--p>
                    Welcome to my blog :
                    <a href="https://blog.naver.com/hummingphant/" class="blog"> <I>EARTH-305</I> </a>
                </p-->
        </div>
        <article>

        </article>
        <p style="text-align:center;"><a id="down"> <a href="#up"> <br><br><br><br> ▲ </a> </p>

        <!--div class="arrow" style="transform: translate(-50%, -50%) rotate(30deg);">♥</div-->

    </section>



    <footer>
        copyright 송영창. All rights reserved.
    </footer>

</body>

</html>

sns_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>블로그</title>
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>